### PR TITLE
upstream 0.15.2

### PR DESCRIPTION
**Pull request by mbostock**
Adds support for:

* private fields
* static initializer blocks
* non-decimal integers with an `n` suffix

### CODE REVIEW

**Comment by sydneypalumbo** [comment]
I know @nebrius was recently working on this, too, but I think ran into an issue with private properties while testing it locally – curious if you were able to sort that out, Bryan? https://github.com/observablehq/lezer/pull/9

**Comment by nebrius** [comment]
> I know @nebrius was recently working on this, too, but I think ran into an issue with private properties while testing it locally – curious if you were able to sort that out, Bryan? #9

I never did figure it out before the holiday break started. If this works for you Mike in a notebook, then let's go with this one.

**Comment by mbostock** [comment]
Oh, sorry Bryan, I missed that you already started this. Here’s the diff in this PR compared to yours:

```patch
diff --git a/src/javascript.grammar b/src/javascript.grammar
index c9adf2a..c41dd48 100644
--- a/src/javascript.grammar
+++ b/src/javascript.grammar
@@ -1,4 +1,6 @@
 @precedence {
+  intersection @left,
+  union @left,
   else @right,
   member,
   newArgs,
@@ -109,7 +111,7 @@ MethodDeclaration[group=ClassItem] {
   pkwMod<"async">?
   (pkwMod<"get"> | pkwMod<"set"> | Star)?
   (PropertyDefinition | PrivatePropertyDefinition)
-  ParamList
+  functionSignature
   Block
 }
 
@@ -119,9 +121,7 @@ StaticBlock[group=ClassItem] {
 
 PropertyDeclaration[group=ClassItem] {
   pkwMod<"static">?
-  pkwMod<"readonly">?
   (PropertyDefinition | PrivatePropertyDefinition)
-  LogicOp<"!">?
   ("=" expressionNoComma)?
   semi
 }
@@ -201,7 +201,7 @@ ArrayExpression {
 propName { PropertyDefinition | "[" expression "]" | Number | String }
 
 Property {
-  pkwMod<"async">? (pkwMod<"get"> | pkwMod<"set"> | Star)? propName ParamList Block |
+  pkwMod<"async">? (pkwMod<"get"> | pkwMod<"set"> | Star)? propName functionSignature Block |
   propName ~destructure (":" expressionNoComma)? |
   "..." expressionNoComma
 }
@@ -215,8 +215,10 @@ ClassExpression {
   kw<"class"> VariableDefinition? (kw<"extends"> expression)? ClassBody
 }
 
+functionSignature { ParamList }
+
 FunctionExpression {
-  async? kw<"function"> Star? VariableDefinition? ParamList Block
+  async? kw<"function"> Star? VariableDefinition? functionSignature Block
 }
 
 UnaryExpression {
```

To summarize:

* The `readonly` and `!` are TypeScript features that should have been removed previously since we don’t (yet) support TypeScript in Observable.
* The introduction of `functionSignature` was added in https://github.com/lezer-parser/javascript/commit/2c69ee2ab55850b01f68021d62a3328a2aec82da; I could remove that since it was only needed for TypeScript, but keeping it makes this slightly easier to maintain.
* The precedence changes were added in https://github.com/lezer-parser/javascript/commit/0740b29bd2d79036c9ff2679c9363564f0a1d17b. This also appears to be TypeScript related but not totally sure…

In what way did the other branch not work locally? I haven’t tested this too thoroughly.

**Comment by nebrius** [comment]
> To summarize:
> 
>     * The `readonly` and `!` are TypeScript features that should have been removed previously since we don’t (yet) support TypeScript in Observable.
> 
>     * The introduction of `functionSignature` was added in [lezer-parser@2c69ee2](https://github.com/lezer-parser/javascript/commit/2c69ee2ab55850b01f68021d62a3328a2aec82da); I could remove that since it was only needed for TypeScript, but keeping it makes this slightly easier to maintain.
> 
>     * The precedence changes were added in [lezer-parser@0740b29](https://github.com/lezer-parser/javascript/commit/0740b29bd2d79036c9ff2679c9363564f0a1d17b). This also appears to be TypeScript related but not totally sure…

Ah yeah, these are good catches and good points.
 
> In what way did the other branch not work locally? I haven’t tested this too thoroughly.

I was getting syntax errors on `#private` properties, saying `#` is invalid (in a notebook). I didn't get far in my testing before the day was up, so it could have been a mistake in how I wired in the dev version of lezer, or it could have been something related to the changes in your diff above.

**Review by sydneypalumbo — APPROVED** [review]
sorry for the delay here, I ran into issues trying to make this work well locally with docker... but it all looks good to me in the diff👍

**Pull request merged**
